---
abstract: 'Aspect-oriented function call tracing'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0.80
  IPC::Run3: 0.042
  Test::More: 0.42
  Test::NoWarnings: 0.084
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Aspect::Library::Trace
name: Aspect-Library-Trace
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Aspect: 1.00
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Aspect-Library-Trace
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Aspect-Library-Trace
version: 1.00
